server:
  port: 8081
logging:
  level:
    com.tumiao.dao: debug

# 文件上传目录配置
# 配置web.upload-path为与项目代码分离的静态资源路径（文件上传保存根路径）
web:
  upload-path: D:/second_images/

# 文件上传配置
minio:
  endpoint: http://43.138.186.222:9000 #minio的ip地址
  accessKey: minio #用户名
  secretKey: minio@123456 #密码

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/secondhand?characterEncoding=utf-8
      username: root
      password: 123456
#      url: jdbc:mysql://43.138.186.222:3306/secondhand?characterEncoding=utf-8
#      username: root
#      password:
  web:
    resources:
      # 该路径下的静态资源能被外界直接访问
      static-locations: classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  servlet:
    multipart: #图片配置设置，最大存储和最大结构
      max-file-size: 1000MB
      max-request-size: 100MB






